version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      timezone: Asia/Jakarta
    open-pull-requests-limit: 7
    commit-message:
      prefix: "chore"
      include: "scope"
